language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - cd ../codesniffer-standards
  - composer selfupdate
  - composer install

script:
  - cd MyCakePHP && phpunit
  - cd ..
	- cd MyCakePHPCore && phpunit

notifications:
  email: false
